import type { Metadata } from 'next'
import ConvexClientProvider from '@/app/_providers/convex-client-provider'
import { Toaster } from '@/shared/components/ui'
import './globals.css'
import ModalProvider from './_providers/modal-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>
          <Toaster />
          <ModalProvider />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  )
}
